"""AI 视频生成内置模板（Phase 6/7）。

模板仅供视频生成使用，与图片渲染模板（RenderPreset）完全隔离。
每个模板包含：名称、适用模式、默认提示词、默认负向提示词、推荐时长/比例/分辨率、
推荐镜头运动、默认建筑约束。
"""

# 建筑视频强约束（默认启用并保存到任务快照）
ARCH_CONSTRAINTS = [
    "锁定建筑主体数量、体量、轮廓、层数",
    "锁定道路、主入口、主要门窗、设备位置",
    "锁定建筑风格与主材质关系",
    "保持首尾帧构图和空间关系",
    "禁止新增/删除建筑主体、楼层、道路或主要设备",
    "禁止建筑扭曲、立面漂移、严重透视错误",
    "禁止乱码文字、虚假项目标识、重复车辆/人物",
    "禁止不合理施工机械、悬浮构件、物理错误",
    "禁止镜头快速乱飘、频繁切镜、无关主体出现",
]

ARCH_NEGATIVE = (
    "禁止新增或删除建筑主体、楼层、道路、主要设备，禁止改变建筑轮廓、体量、层数，"
    "禁止建筑扭曲、立面漂移、严重透视错误，禁止乱码文字、虚假项目标识、重复车辆/人物，"
    "禁止不合理施工机械、悬浮构件、物理错误，禁止镜头快速乱飘、频繁切镜、无关主体出现"
)

# 42 个 EVAI img2Video 模板（2026-08-19 抓取自 https://www.openevai.com/img2Video）
# 分类：建筑外景运镜（image_to_video，12 个）/ 首尾帧·创意运镜（first_last_frame_video，30 个）
SYSTEM_TEMPLATES = [
    {
        "name": "建筑平移",
        "description": "镜头逐渐向左平移，光影在变化，匀速",
        "applicable_modes": ["image_to_video"],
        "default_positive_prompt": "镜头逐渐向左平移，光影在变化，匀速",
        "recommended_duration": 5,
        "recommended_aspect_ratio": "16:9",
        "recommended_resolution": "720p",
        "recommended_camera_motion": "立面展示 / 街景",
        "source_template_id": "evai_36",
    },
    {
        "name": "建筑鸟瞰环绕",
        "description": "俯拍建筑，环绕拍摄，人来人往，车来车往，光影变化，云朵飘动",
        "applicable_modes": ["image_to_video"],
        "default_positive_prompt": "俯拍建筑，环绕拍摄，人来人往，车来车往，光影变化，云朵飘动",
        "recommended_duration": 5,
        "recommended_aspect_ratio": "16:9",
        "recommended_resolution": "720p",
        "recommended_camera_motion": "场地分析 / 规划",
        "source_template_id": "evai_37",
    },
    {
        "name": "建筑从整体到局部",
        "description": "镜头逐渐下降，停留在建筑的主入口处",
        "applicable_modes": ["image_to_video"],
        "default_positive_prompt": "镜头逐渐下降，停留在建筑的主入口处",
        "recommended_duration": 5,
        "recommended_aspect_ratio": "16:9",
        "recommended_resolution": "720p",
        "recommended_camera_motion": "入口节点 / 定位",
        "source_template_id": "evai_38",
    },
    {
        "name": "建筑从室外到室内",
        "description": "镜头向主入口推进，入口玻璃门打开，进入室内",
        "applicable_modes": ["image_to_video"],
        "default_positive_prompt": "镜头向主入口推进，入口玻璃门打开，进入室内",
        "recommended_duration": 5,
        "recommended_aspect_ratio": "16:9",
        "recommended_resolution": "720p",
        "recommended_camera_motion": "空间过渡 / 贯通",
        "source_template_id": "evai_39",
    },
    {
        "name": "希区柯克推进",
        "description": "镜头快速在建筑上空沿着左下侧飞向右上侧方向快速推进",
        "applicable_modes": ["image_to_video"],
        "default_positive_prompt": "镜头快速在建筑上空沿着左下侧飞向右上侧方向快速推进",
        "recommended_duration": 5,
        "recommended_aspect_ratio": "16:9",
        "recommended_resolution": "720p",
        "recommended_camera_motion": "视觉冲击 / 概念",
        "source_template_id": "evai_40",
    },
    {
        "name": "中心环绕",
        "description": "镜头沿着画面中间的主要建筑环绕",
        "applicable_modes": ["image_to_video"],
        "default_positive_prompt": "镜头沿着画面中间的主要建筑环绕",
        "recommended_duration": 5,
        "recommended_aspect_ratio": "16:9",
        "recommended_resolution": "720p",
        "recommended_camera_motion": "单体建筑 / 雕塑",
        "source_template_id": "evai_41",
    },
    {
        "name": "起重机",
        "description": "FPV镜头，镜头从下往上快速推进，最后俯瞰写字楼",
        "applicable_modes": ["image_to_video"],
        "default_positive_prompt": "FPV镜头，镜头从下往上快速推进，最后俯瞰写字楼",
        "recommended_duration": 5,
        "recommended_aspect_ratio": "16:9",
        "recommended_resolution": "720p",
        "recommended_camera_motion": "高层塔楼 / 气势",
        "source_template_id": "evai_42",
    },
    {
        "name": "超级拉远",
        "description": "镜头拉远，展示城市总体规划图，再到卫星地图",
        "applicable_modes": ["image_to_video"],
        "default_positive_prompt": "镜头拉远，展示城市总体规划图，再到卫星地图",
        "recommended_duration": 5,
        "recommended_aspect_ratio": "16:9",
        "recommended_resolution": "720p",
        "recommended_camera_motion": "城市区位 / 宏观",
        "source_template_id": "evai_43",
    },
    {
        "name": "延时摄影",
        "description": "镜头固定，从天亮一直拍到天黑，用延时摄影",
        "applicable_modes": ["image_to_video"],
        "default_positive_prompt": "镜头固定，从天亮一直拍到天黑，用延时摄影",
        "recommended_duration": 5,
        "recommended_aspect_ratio": "16:9",
        "recommended_resolution": "720p",
        "recommended_camera_motion": "光影分析 / 氛围",
        "source_template_id": "evai_44",
    },
    {
        "name": "俯瞰➕环绕",
        "description": "镜头从高空俯视建筑，捕捉建筑的顶部全貌后，缓慢旋转，使镜头以建筑为中心",
        "applicable_modes": ["image_to_video"],
        "default_positive_prompt": "镜头从高空俯视建筑，捕捉建筑的顶部全貌后，缓慢旋转，使镜头以建筑为中心",
        "recommended_duration": 5,
        "recommended_aspect_ratio": "16:9",
        "recommended_resolution": "720p",
        "recommended_camera_motion": "屋顶结构 / 布局",
        "source_template_id": "evai_45",
    },
    {
        "name": "推进+仰拍",
        "description": "镜头先靠近大楼，从地面开始拍地基，然后把镜头垂直往上抬，贴着大楼外面往上拍，一直抬到楼顶",
        "applicable_modes": ["image_to_video"],
        "default_positive_prompt": "镜头先靠近大楼，从地面开始拍地基，然后把镜头垂直往上抬，贴着大楼外面往上拍，一直抬到楼顶",
        "recommended_duration": 5,
        "recommended_aspect_ratio": "16:9",
        "recommended_resolution": "720p",
        "recommended_camera_motion": "建筑高度 / 仰视",
        "source_template_id": "evai_46",
    },
    {
        "name": "拉远",
        "description": "镜头逐渐推向远景，展现整个建筑，天空的清新蓝色背景增添视觉效果",
        "applicable_modes": ["image_to_video"],
        "default_positive_prompt": "镜头逐渐推向远景，展现整个建筑，天空的清新蓝色背景增添视觉效果",
        "recommended_duration": 5,
        "recommended_aspect_ratio": "16:9",
        "recommended_resolution": "720p",
        "recommended_camera_motion": "全貌展示 / 结尾",
        "source_template_id": "evai_47",
    },
    {
        "name": "建筑生长动画",
        "description": "一栋建筑从地面逐渐向上生长出来，固定鏡头。",
        "applicable_modes": ["first_last_frame_video"],
        "default_positive_prompt": "一栋建筑从地面逐渐向上生长出来，固定鏡头。",
        "recommended_duration": 5,
        "recommended_aspect_ratio": "adaptive",
        "recommended_resolution": "720p",
        "recommended_camera_motion": "首尾帧过渡",
        "source_template_id": "evai_60",
    },
    {
        "name": "城市生长动画",
        "description": "城市生长动画",
        "applicable_modes": ["first_last_frame_video"],
        "default_positive_prompt": "城市生长动画",
        "recommended_duration": 5,
        "recommended_aspect_ratio": "adaptive",
        "recommended_resolution": "720p",
        "recommended_camera_motion": "首尾帧过渡",
        "source_template_id": "evai_3",
    },
    {
        "name": "建筑像火箭一样升空",
        "description": "建筑像火箭一样升空",
        "applicable_modes": ["first_last_frame_video"],
        "default_positive_prompt": "建筑像火箭一样升空",
        "recommended_duration": 5,
        "recommended_aspect_ratio": "adaptive",
        "recommended_resolution": "720p",
        "recommended_camera_motion": "首尾帧过渡",
        "source_template_id": "evai_1",
    },
    {
        "name": "线稿转实景图",
        "description": "线稿转实景图",
        "applicable_modes": ["first_last_frame_video"],
        "default_positive_prompt": "线稿转实景图",
        "recommended_duration": 5,
        "recommended_aspect_ratio": "adaptive",
        "recommended_resolution": "720p",
        "recommended_camera_motion": "首尾帧过渡",
        "source_template_id": "evai_10",
    },
    {
        "name": "根据这张城市公园中的多层图书馆的建筑俯视图，生成对应的低空平视规划实景照片",
        "description": "根据这张城市公园中的多层图书馆的建筑俯视图，生成对应的低空平视规划实景照片",
        "applicable_modes": ["first_last_frame_video"],
        "default_positive_prompt": "根据这张城市公园中的多层图书馆的建筑俯视图，生成对应的低空平视规划实景照片",
        "recommended_duration": 5,
        "recommended_aspect_ratio": "adaptive",
        "recommended_resolution": "720p",
        "recommended_camera_motion": "首尾帧过渡",
        "source_template_id": "evai_11",
    },
    {
        "name": "视角转换",
        "description": "视角转换",
        "applicable_modes": ["first_last_frame_video"],
        "default_positive_prompt": "视角转换",
        "recommended_duration": 5,
        "recommended_aspect_ratio": "adaptive",
        "recommended_resolution": "720p",
        "recommended_camera_motion": "首尾帧过渡",
        "source_template_id": "evai_12",
    },
    {
        "name": "建筑工人施工将建筑的立面材质改为红砖",
        "description": "建筑工人施工将建筑的立面材质改为红砖",
        "applicable_modes": ["first_last_frame_video"],
        "default_positive_prompt": "建筑工人施工将建筑的立面材质改为红砖",
        "recommended_duration": 5,
        "recommended_aspect_ratio": "adaptive",
        "recommended_resolution": "720p",
        "recommended_camera_motion": "首尾帧过渡",
        "source_template_id": "evai_13",
    },
    {
        "name": "天气转变为大雾天气，固定视角，延时摄影",
        "description": "天气转变为大雾天气，固定视角，延时摄影",
        "applicable_modes": ["first_last_frame_video"],
        "default_positive_prompt": "天气转变为大雾天气，固定视角，延时摄影",
        "recommended_duration": 5,
        "recommended_aspect_ratio": "adaptive",
        "recommended_resolution": "720p",
        "recommended_camera_motion": "首尾帧过渡",
        "source_template_id": "evai_14",
    },
    {
        "name": "从白天到日落，固定视角，延时摄影",
        "description": "从白天到日落，固定视角，延时摄影",
        "applicable_modes": ["first_last_frame_video"],
        "default_positive_prompt": "从白天到日落，固定视角，延时摄影",
        "recommended_duration": 5,
        "recommended_aspect_ratio": "adaptive",
        "recommended_resolution": "720p",
        "recommended_camera_motion": "首尾帧过渡",
        "source_template_id": "evai_15",
    },
    {
        "name": "将图片中的氛围切换到夜晚，突出建筑内的灯光照明",
        "description": "将图片中的氛围切换到夜晚，突出建筑内的灯光照明",
        "applicable_modes": ["first_last_frame_video"],
        "default_positive_prompt": "将图片中的氛围切换到夜晚，突出建筑内的灯光照明",
        "recommended_duration": 5,
        "recommended_aspect_ratio": "adaptive",
        "recommended_resolution": "720p",
        "recommended_camera_motion": "首尾帧过渡",
        "source_template_id": "evai_16",
    },
    {
        "name": "图片中的天气切换为冬天，白雪覆盖建筑地面树木",
        "description": "图片中的天气切换为冬天，白雪覆盖建筑地面树木",
        "applicable_modes": ["first_last_frame_video"],
        "default_positive_prompt": "图片中的天气切换为冬天，白雪覆盖建筑地面树木",
        "recommended_duration": 5,
        "recommended_aspect_ratio": "adaptive",
        "recommended_resolution": "720p",
        "recommended_camera_motion": "首尾帧过渡",
        "source_template_id": "evai_18",
    },
    {
        "name": "变成微缩景观",
        "description": "变成微缩景观",
        "applicable_modes": ["first_last_frame_video"],
        "default_positive_prompt": "变成微缩景观",
        "recommended_duration": 5,
        "recommended_aspect_ratio": "adaptive",
        "recommended_resolution": "720p",
        "recommended_camera_motion": "首尾帧过渡",
        "source_template_id": "evai_19",
    },
    {
        "name": "白纸平整的置于桌面上，镜头快速由远景推近，紧接着环绕纸张进行旋转，以纸张为中心，线条开始如灵动的精灵般浮现交织，色彩逐渐晕染开来，随着镜头缓缓上升，画面中的线条与色彩不断汇聚、组合。建筑得轮廓逐渐清晰，最终画面定格在建筑图，这座宏伟的建筑完美呈现，仿佛从这张白纸之上拔地而起",
        "description": "白纸平整的置于桌面上，镜头快速由远景推近，紧接着环绕纸张进行旋转，以纸张为中心，线条开始如灵动的精灵般浮现交织，色彩逐渐晕染开来，随着镜头缓缓上升，画面中的线条与色彩不断汇聚、组合。建筑得轮廓逐渐清晰，最终画面定格在建筑图，这座宏伟的建筑完美呈现，仿佛从这张白纸之上拔地而起",
        "applicable_modes": ["first_last_frame_video"],
        "default_positive_prompt": "白纸平整的置于桌面上，镜头快速由远景推近，紧接着环绕纸张进行旋转，以纸张为中心，线条开始如灵动的精灵般浮现交织，色彩逐渐晕染开来，随着镜头缓缓上升，画面中的线条与色彩不断汇聚、组合。建筑得轮廓逐渐清晰，最终画面定格在建筑图，这座宏伟的建筑完美呈现，仿佛从这张白纸之上拔地而起",
        "recommended_duration": 5,
        "recommended_aspect_ratio": "adaptive",
        "recommended_resolution": "720p",
        "recommended_camera_motion": "首尾帧过渡",
        "source_template_id": "evai_2",
    },
    {
        "name": "变成微缩模型",
        "description": "变成微缩模型",
        "applicable_modes": ["first_last_frame_video"],
        "default_positive_prompt": "变成微缩模型",
        "recommended_duration": 5,
        "recommended_aspect_ratio": "adaptive",
        "recommended_resolution": "720p",
        "recommended_camera_motion": "首尾帧过渡",
        "source_template_id": "evai_20",
    },
    {
        "name": "街道翻新",
        "description": "街道翻新",
        "applicable_modes": ["first_last_frame_video"],
        "default_positive_prompt": "街道翻新",
        "recommended_duration": 5,
        "recommended_aspect_ratio": "adaptive",
        "recommended_resolution": "720p",
        "recommended_camera_motion": "首尾帧过渡",
        "source_template_id": "evai_21",
    },
    {
        "name": "根据手稿生成建筑",
        "description": "根据手稿生成建筑",
        "applicable_modes": ["first_last_frame_video"],
        "default_positive_prompt": "根据手稿生成建筑",
        "recommended_duration": 5,
        "recommended_aspect_ratio": "adaptive",
        "recommended_resolution": "720p",
        "recommended_camera_motion": "首尾帧过渡",
        "source_template_id": "evai_22",
    },
    {
        "name": "色彩从中心晕开",
        "description": "色彩从中心晕开",
        "applicable_modes": ["first_last_frame_video"],
        "default_positive_prompt": "色彩从中心晕开",
        "recommended_duration": 5,
        "recommended_aspect_ratio": "adaptive",
        "recommended_resolution": "720p",
        "recommended_camera_motion": "首尾帧过渡",
        "source_template_id": "evai_23",
    },
    {
        "name": "对建筑进行设计标注",
        "description": "对建筑进行设计标注",
        "applicable_modes": ["first_last_frame_video"],
        "default_positive_prompt": "对建筑进行设计标注",
        "recommended_duration": 5,
        "recommended_aspect_ratio": "adaptive",
        "recommended_resolution": "720p",
        "recommended_camera_motion": "首尾帧过渡",
        "source_template_id": "evai_24",
    },
    {
        "name": "生成建筑爆炸图",
        "description": "生成建筑爆炸图",
        "applicable_modes": ["first_last_frame_video"],
        "default_positive_prompt": "生成建筑爆炸图",
        "recommended_duration": 5,
        "recommended_aspect_ratio": "adaptive",
        "recommended_resolution": "720p",
        "recommended_camera_motion": "首尾帧过渡",
        "source_template_id": "evai_25",
    },
    {
        "name": "两名女士走到沙发上聊天",
        "description": "两名女士走到沙发上聊天",
        "applicable_modes": ["first_last_frame_video"],
        "default_positive_prompt": "两名女士走到沙发上聊天",
        "recommended_duration": 5,
        "recommended_aspect_ratio": "adaptive",
        "recommended_resolution": "720p",
        "recommended_camera_motion": "首尾帧过渡",
        "source_template_id": "evai_26",
    },
    {
        "name": "建筑工人对房屋进行翻新装修",
        "description": "建筑工人对房屋进行翻新装修",
        "applicable_modes": ["first_last_frame_video"],
        "default_positive_prompt": "建筑工人对房屋进行翻新装修",
        "recommended_duration": 5,
        "recommended_aspect_ratio": "adaptive",
        "recommended_resolution": "720p",
        "recommended_camera_motion": "首尾帧过渡",
        "source_template_id": "evai_27",
    },
    {
        "name": "生成建筑轴测模型",
        "description": "生成建筑轴测模型",
        "applicable_modes": ["first_last_frame_video"],
        "default_positive_prompt": "生成建筑轴测模型",
        "recommended_duration": 5,
        "recommended_aspect_ratio": "adaptive",
        "recommended_resolution": "720p",
        "recommended_camera_motion": "首尾帧过渡",
        "source_template_id": "evai_28",
    },
    {
        "name": "卡通人物走到沙发上交流",
        "description": "卡通人物走到沙发上交流",
        "applicable_modes": ["first_last_frame_video"],
        "default_positive_prompt": "卡通人物走到沙发上交流",
        "recommended_duration": 5,
        "recommended_aspect_ratio": "adaptive",
        "recommended_resolution": "720p",
        "recommended_camera_motion": "首尾帧过渡",
        "source_template_id": "evai_29",
    },
    {
        "name": "两个卡通人物走到咖啡厅门前喝咖啡",
        "description": "两个卡通人物走到咖啡厅门前喝咖啡",
        "applicable_modes": ["first_last_frame_video"],
        "default_positive_prompt": "两个卡通人物走到咖啡厅门前喝咖啡",
        "recommended_duration": 5,
        "recommended_aspect_ratio": "adaptive",
        "recommended_resolution": "720p",
        "recommended_camera_motion": "首尾帧过渡",
        "source_template_id": "evai_30",
    },
    {
        "name": "创建这座建筑的剖面图，一侧显示完整的外部结构，另一侧显示内部的结构以及装修细节。保持比例准确，细节逼真。",
        "description": "创建这座建筑的剖面图，一侧显示完整的外部结构，另一侧显示内部的结构以及装修细节。保持比例准确，细节逼真。",
        "applicable_modes": ["first_last_frame_video"],
        "default_positive_prompt": "创建这座建筑的剖面图，一侧显示完整的外部结构，另一侧显示内部的结构以及装修细节。保持比例准确，细节逼真。",
        "recommended_duration": 5,
        "recommended_aspect_ratio": "adaptive",
        "recommended_resolution": "720p",
        "recommended_camera_motion": "首尾帧过渡",
        "source_template_id": "evai_4",
    },
    {
        "name": "绘制一个 A6 折叠卡：打开时它会展示一个完整的 3D 球形小屋，里面有一座微型的纸花园和盆景树。",
        "description": "绘制一个 A6 折叠卡：打开时它会展示一个完整的 3D 球形小屋，里面有一座微型的纸花园和盆景树。",
        "applicable_modes": ["first_last_frame_video"],
        "default_positive_prompt": "绘制一个 A6 折叠卡：打开时它会展示一个完整的 3D 球形小屋，里面有一座微型的纸花园和盆景树。",
        "recommended_duration": 5,
        "recommended_aspect_ratio": "adaptive",
        "recommended_resolution": "720p",
        "recommended_camera_motion": "首尾帧过渡",
        "source_template_id": "evai_5",
    },
    {
        "name": "把这张建筑线稿图转成实景照片，要求摄影质感，真实的光影效果。阴天乌云密布，建筑里透出灯光，建筑前有零星的行人。保持画面结构不变。",
        "description": "把这张建筑线稿图转成实景照片，要求摄影质感，真实的光影效果。阴天乌云密布，建筑里透出灯光，建筑前有零星的行人。保持画面结构不变。",
        "applicable_modes": ["first_last_frame_video"],
        "default_positive_prompt": "把这张建筑线稿图转成实景照片，要求摄影质感，真实的光影效果。阴天乌云密布，建筑里透出灯光，建筑前有零星的行人。保持画面结构不变。",
        "recommended_duration": 5,
        "recommended_aspect_ratio": "adaptive",
        "recommended_resolution": "720p",
        "recommended_camera_motion": "首尾帧过渡",
        "source_template_id": "evai_6",
    },
    {
        "name": "将图片变真实",
        "description": "将图片变真实",
        "applicable_modes": ["first_last_frame_video"],
        "default_positive_prompt": "将图片变真实",
        "recommended_duration": 5,
        "recommended_aspect_ratio": "adaptive",
        "recommended_resolution": "720p",
        "recommended_camera_motion": "首尾帧过渡",
        "source_template_id": "evai_7",
    },
    {
        "name": "从红色圆圈沿箭头方向画出真实世界的视角",
        "description": "从红色圆圈沿箭头方向画出真实世界的视角",
        "applicable_modes": ["first_last_frame_video"],
        "default_positive_prompt": "从红色圆圈沿箭头方向画出真实世界的视角",
        "recommended_duration": 5,
        "recommended_aspect_ratio": "adaptive",
        "recommended_resolution": "720p",
        "recommended_camera_motion": "首尾帧过渡",
        "source_template_id": "evai_8",
    },
    {
        "name": "装修工人对房间进行布置",
        "description": "装修工人对房间进行布置",
        "applicable_modes": ["first_last_frame_video"],
        "default_positive_prompt": "装修工人对房间进行布置",
        "recommended_duration": 5,
        "recommended_aspect_ratio": "adaptive",
        "recommended_resolution": "720p",
        "recommended_camera_motion": "首尾帧过渡",
        "source_template_id": "evai_9",
    },
]
